"use client";
/** Exports: analysis summary/report (Markdown), questions (CSV), notebook (CSV), full data (JSON). */
import { breakdown, errorBreakdown, explainChange, scoreAnalysis, topLossSources, type Recommendation } from "@/domain/analysis";
import { formatKey, formatResponse, STATUS_LABEL } from "@/domain/scoring";
import type { Analysis, AppData, ErrorCategory, NotebookEntry } from "@/domain/types";
import { fmtNum, pct, fmtPct1 } from "@/domain/util";

export function download(filename: string, content: string | Blob, type = "text/plain") {
  const blob = typeof content === "string" ? new Blob([content], { type: `${type};charset=utf-8` }) : content;
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

export const slug = (s: string) => s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 60) || "export";

function csvCell(v: unknown): string {
  const s = v === undefined || v === null ? "" : String(v);
  // Neutralise spreadsheet formula injection and quote when needed. Plain numbers
  // (e.g. −1 marks) stay numbers so spreadsheets can still add them up.
  const isNumber = typeof v === "number" || /^-?\d+(\.\d+)?$/.test(s);
  const safe = !isNumber && /^[=+\-@\t\r]/.test(s) ? `'${s}` : s;
  return /[",\n]/.test(safe) ? `"${safe.replace(/"/g, '""')}"` : safe;
}
export function toCsv(rows: unknown[][]): string {
  return rows.map((r) => r.map(csvCell).join(",")).join("\n");
}

export function questionsCsv(a: Analysis, cats: ErrorCategory[]): string {
  const s = scoreAnalysis(a);
  const label = new Map(cats.map((c) => [c.id, c.label]));
  const rows: unknown[][] = [["Q", "Printed no.", "Section", "Subject", "Chapter", "Topic", "Type", "Your answer", "Correct answer", "Status", "Marks", "Marks short", "Guessed", "Out of time", "Time (s)", "Error type", "Secondary", "Note", "Question text"]];
  for (const q of [...a.questions].sort((x, y) => x.index - y.index)) {
    const r = a.responses[q.id];
    const res = s.byId[q.id];
    rows.push([
      q.index, q.number, a.sections.find((x) => x.id === q.sectionId)?.name, q.subject, q.chapter, q.topic, q.type, formatResponse(q, r), formatKey(q),
      res ? STATUS_LABEL[res.status] : "", res?.awarded, res?.forfeited, r?.guessed ? "yes" : "", r?.outOfTime ? "yes" : "", r?.timeSpentSec ?? "",
      r?.errorPrimary ? (r.errorPrimary === "unknown" ? "Review later" : label.get(r.errorPrimary) ?? r.errorPrimary) : "",
      (r?.errorSecondary ?? []).map((x) => label.get(x) ?? x).join("; "), r?.errorNote ?? "", q.text,
    ]);
  }
  return toCsv(rows);
}

export function notebookCsv(entries: NotebookEntry[], analyses: Analysis[], cats: ErrorCategory[]): string {
  const label = new Map(cats.map((c) => [c.id, c.label]));
  const rows: unknown[][] = [["Exam", "Question", "Subject", "Chapter", "Topic", "Error type", "Your answer", "Correct answer", "What went wrong", "Corrected approach", "Retries", "Last retry", "Next retry", "Mastery"]];
  for (const n of entries) {
    const a = analyses.find((x) => x.id === n.analysisId);
    const q = a?.questions.find((x) => x.id === n.questionId);
    const last = n.retries[n.retries.length - 1];
    rows.push([a?.title, q ? `Q${q.index}` : "", n.subject, n.chapter, n.topic, label.get(n.errorType) ?? n.errorType, n.studentAnswer, n.correctAnswer, n.whatWentWrong, n.correctedApproach,
      n.retries.length, last ? `${last.at.slice(0, 10)} ${last.correct ? "correct" : "wrong"}` : "", n.nextRetryAt ?? "", n.mastery]);
  }
  return toCsv(rows);
}

export function reportMarkdown(a: Analysis, cats: ErrorCategory[], recs: Recommendation[], previous?: Analysis): string {
  const s = scoreAnalysis(a);
  const lines: string[] = [];
  lines.push(`# ${a.title} — Exam analysis`, "", `Taken ${a.takenOn} · ${a.questions.length} questions · generated by Student OS`, "");
  lines.push("## 1. Score summary", "", `- **Score:** ${fmtNum(s.score)} / ${fmtNum(s.maxScore)} (${fmtPct1(s.percentage)})`,
    `- **Attempt accuracy:** ${pct(s.accuracy)} (${s.correct} correct ÷ ${s.attempted} attempted)`,
    `- **Attempt rate:** ${pct(s.attemptRate)} (${s.attempted} of ${s.gradable})`,
    `- **Correct / wrong / unattempted:** ${s.correct} / ${s.wrong} / ${s.unattempted}${s.partial ? ` · partial ${s.partial}` : ""}`,
    `- **Negative-mark impact:** −${fmtNum(s.negativeImpact)}`, "");
  lines.push("## 2. Where the marks went", "", `- Left unattempted: −${fmtNum(s.forfeitedUnattempted)}`, `- Wrong answers (marks not earned + penalties): −${fmtNum(s.forfeitedWrong)}`, s.forfeitedPartial ? `- Partial-credit shortfall: −${fmtNum(s.forfeitedPartial)}` : "", "");
  lines.push("## 3. By subject", "", "| Subject | Score | Correct | Wrong | Unattempted | Accuracy |", "|---|---|---|---|---|---|");
  for (const r of breakdown(a, s, "subject")) lines.push(`| ${r.subject} | ${fmtNum(r.score)}/${fmtNum(r.max)} | ${r.correct} | ${r.wrong} | ${r.unattempted} | ${pct(r.accuracy)} |`);
  lines.push("", "## 4. Top mark-loss sources", "");
  for (const t of topLossSources(a, s, cats, 6)) lines.push(`- **${t.chapter}** (${t.subject}): −${fmtNum(t.forfeited)} — ${t.wrong} wrong, ${t.unattempted} unattempted${t.dominantError ? `; mostly ${t.dominantError.label.toLowerCase()}` : ""}`);
  lines.push("", "## 5. Why marks were lost", "");
  for (const e of errorBreakdown(a, s, cats)) lines.push(`- ${e.label}: ${e.count} question${e.count === 1 ? "" : "s"}, −${fmtNum(e.forfeited)}`);
  lines.push("", "## 6. Recommended next actions", "");
  recs.forEach((r, i) => lines.push(`${i + 1}. **${r.title}** — ${r.detail}  \n   _Evidence: ${r.reason}_`));
  if (previous) {
    const e = explainChange(s, scoreAnalysis(previous));
    lines.push("", "## 7. Compared with the previous test", "", `${previous.title}: ${fmtNum(scoreAnalysis(previous).score)} → ${fmtNum(s.score)}. ${e.narrative}`);
  }
  lines.push("", "## Questions to redo", "");
  for (const q of a.questions.filter((x) => s.byId[x.id]?.status === "wrong").sort((x, y) => x.index - y.index)) {
    const r = a.responses[q.id];
    lines.push(`- Q${q.index} (${q.chapter || q.subject}): you ${formatResponse(q, r)}, key ${formatKey(q)}${r?.errorPrimary ? ` — ${cats.find((c) => c.id === r.errorPrimary)?.label ?? r.errorPrimary}` : ""}`);
  }
  return lines.filter((l, i, arr) => !(l === "" && arr[i - 1] === "")).join("\n");
}

export function backupJson(data: AppData): string {
  return JSON.stringify({ app: "student-os", exportedAt: new Date().toISOString(), data }, null, 2);
}

/** Backups bigger than this aren't real (a heavy user's data is a few MB). */
export const MAX_BACKUP_MB = 50;
const ISO_DATE = /^\d{4}-\d{2}-\d{2}$/;
const MAX_ITEMS = 200_000;

type Rec = Record<string, unknown>;
const isObj = (v: unknown): v is Rec => !!v && typeof v === "object" && !Array.isArray(v);
const isStr = (v: unknown): v is string => typeof v === "string";
const isNum = (v: unknown): v is number => typeof v === "number" && Number.isFinite(v);
const isDate = (v: unknown) => isStr(v) && ISO_DATE.test(v.slice(0, 10));
const optional = (v: unknown, ok: (x: unknown) => boolean) => v === undefined || v === null || ok(v);

/** Checks every collection item has the fields the app relies on, with the right types. */
const RULES: Record<string, (x: Rec) => boolean> = {
  exams: (x) => isStr(x.name) && isDate(x.date) && Array.isArray(x.subjects) && x.subjects.every(isStr) && Array.isArray(x.sections) && x.sections.every(isObj),
  topics: (x) => isStr(x.examId) && isStr(x.subject) && isStr(x.chapter) && isStr(x.topic),
  analyses: (x) => isStr(x.examId) && isStr(x.title) && isDate(x.takenOn) && Array.isArray(x.questions) && x.questions.every((q) => isObj(q) && isStr(q.id))
    && Array.isArray(x.sections) && isObj(x.responses) && optional(x.changes, Array.isArray),
  tasks: (x) => isStr(x.examId) && isStr(x.title) && isDate(x.dueDate) && isNum(x.durationMinutes) && ["pending", "done", "skipped"].includes(x.status as string)
    && ["high", "medium", "low"].includes(x.priority as string) && isStr(x.type),
  revisions: (x) => isStr(x.examId) && isDate(x.dueAt) && isStr(x.label),
  notebook: (x) => isStr(x.analysisId) && isStr(x.questionId) && optional(x.nextRetryAt, isDate) && Array.isArray(x.retries),
  practiceSets: (x) => isStr(x.name) && Array.isArray(x.items),
  planChanges: (x) => isStr(x.examId) && isStr(x.at) && Array.isArray(x.details) && x.details.every(isStr),
};

/**
 * Reads a backup file. Rejects anything that isn't a well-formed Student OS backup, and keeps
 * only the known fields, so a crafted file can't replace the app's own functions or crash it.
 */
export function parseBackup(text: string): AppData {
  if (text.length > MAX_BACKUP_MB * 1024 * 1024) throw new Error(`This file is too big to be an Student OS backup (over ${MAX_BACKUP_MB} MB).`);
  let parsed: unknown;
  try {
    parsed = JSON.parse(text);
  } catch {
    throw new Error("This file isn't an Student OS backup (it isn't a backup file at all).");
  }
  const data = isObj(parsed) && isObj(parsed.data) ? parsed.data : parsed;
  if (!isObj(data) || !Array.isArray(data.exams) || !Array.isArray(data.analyses) || !isObj(data.settings)) throw new Error("This file isn't an Student OS backup.");
  const invalid = (why: string) => new Error(`This file isn't a valid Student OS backup: ${why}. Nothing was changed.`);

  const out: Rec = {};
  for (const [key, ok] of Object.entries(RULES)) {
    const list = data[key] ?? [];
    if (!Array.isArray(list) || list.length > MAX_ITEMS) throw invalid(`“${key}” is not a list`);
    list.forEach((item, i) => {
      if (!isObj(item) || !isStr(item.id) || !ok(item)) throw invalid(`${key} item ${i + 1} is damaged`);
    });
    out[key] = list;
  }

  const st = data.settings;
  const planner = st.planner;
  if (!optional(st.theme, (t) => ["system", "light", "dark"].includes(t as string))) throw invalid("the theme setting is damaged");
  if (!optional(st.studentName, isStr)) throw invalid("the name setting is damaged");
  if (!optional(planner, (p) => isObj(p) && Array.isArray(p.minutesByWeekday) && p.minutesByWeekday.length === 7 && p.minutesByWeekday.every(isNum)
    && Array.isArray(p.blockedDates) && p.blockedDates.every(isDate))) throw invalid("the study-time settings are damaged");
  if (!optional(st.errorCategories, (c) => Array.isArray(c) && c.every((x) => isObj(x) && isStr(x.id) && isStr(x.label)))) throw invalid("the error categories are damaged");
  if (!optional(data.planMeta, (m) => isObj(m) && Object.values(m).every(isDate))) throw invalid("plan dates are damaged");

  return {
    ...(out as unknown as Omit<AppData, "version" | "settings" | "planMeta" | "isDemo">),
    version: isNum(data.version) ? data.version : 1,
    settings: data.settings as unknown as AppData["settings"],
    planMeta: (data.planMeta as AppData["planMeta"]) ?? {},
    isDemo: data.isDemo === true,
  };
}
