"use client";
/** Exports: analysis summary/report (Markdown), questions (CSV), notebook (CSV), full data (JSON). */
import { breakdown, errorBreakdown, explainChange, scoreAnalysis, topLossSources, type Recommendation } from "@/domain/analysis";
import { formatKey, formatResponse, STATUS_LABEL } from "@/domain/scoring";
import type { Analysis, AppData, ErrorCategory, NotebookEntry } from "@/domain/types";
import { fmtNum, pct, fmtPct1 } from "@/domain/util";

export function download(filename: string, content: string | Blob, type = "text/plain") {
  const blob = typeof content === "string" ? new Blob([content], { type: `${type};charset=utf-8` }) : content;
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

export const slug = (s: string) => s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 60) || "export";

function csvCell(v: unknown): string {
  const s = v === undefined || v === null ? "" : String(v);
  // Neutralise spreadsheet formula injection and quote when needed. Plain numbers
  // (e.g. −1 marks) stay numbers so spreadsheets can still add them up.
  const isNumber = typeof v === "number" || /^-?\d+(\.\d+)?$/.test(s);
  const safe = !isNumber && /^[=+\-@\t\r]/.test(s) ? `'${s}` : s;
  return /[",\n]/.test(safe) ? `"${safe.replace(/"/g, '""')}"` : safe;
}
export function toCsv(rows: unknown[][]): string {
  return rows.map((r) => r.map(csvCell).join(",")).join("\n");
}

export function questionsCsv(a: Analysis, cats: ErrorCategory[]): string {
  const s = scoreAnalysis(a);
  const label = new Map(cats.map((c) => [c.id, c.label]));
  const rows: unknown[][] = [["Q", "Printed no.", "Section", "Subject", "Chapter", "Topic", "Type", "Your answer", "Correct answer", "Status", "Marks", "Marks short", "Guessed", "Out of time", "Time (s)", "Error type", "Secondary", "Note", "Question text"]];
  for (const q of [...a.questions].sort((x, y) => x.index - y.index)) {
    const r = a.responses[q.id];
    const res = s.byId[q.id];
    rows.push([
      q.index, q.number, a.sections.find((x) => x.id === q.sectionId)?.name, q.subject, q.chapter, q.topic, q.type, formatResponse(q, r), formatKey(q),
      res ? STATUS_LABEL[res.status] : "", res?.awarded, res?.forfeited, r?.guessed ? "yes" : "", r?.outOfTime ? "yes" : "", r?.timeSpentSec ?? "",
      r?.errorPrimary ? (r.errorPrimary === "unknown" ? "Review later" : label.get(r.errorPrimary) ?? r.errorPrimary) : "",
      (r?.errorSecondary ?? []).map((x) => label.get(x) ?? x).join("; "), r?.errorNote ?? "", q.text,
    ]);
  }
  return toCsv(rows);
}

export function notebookCsv(entries: NotebookEntry[], analyses: Analysis[], cats: ErrorCategory[]): string {
  const label = new Map(cats.map((c) => [c.id, c.label]));
  const rows: unknown[][] = [["Exam", "Question", "Subject", "Chapter", "Topic", "Error type", "Your answer", "Correct answer", "What went wrong", "Corrected approach", "Retries", "Last retry", "Next retry", "Mastery"]];
  for (const n of entries) {
    const a = analyses.find((x) => x.id === n.analysisId);
    const q = a?.questions.find((x) => x.id === n.questionId);
    const last = n.retries[n.retries.length - 1];
    rows.push([a?.title, q ? `Q${q.index}` : "", n.subject, n.chapter, n.topic, label.get(n.errorType) ?? n.errorType, n.studentAnswer, n.correctAnswer, n.whatWentWrong, n.correctedApproach,
      n.retries.length, last ? `${last.at.slice(0, 10)} ${last.correct ? "correct" : "wrong"}` : "", n.nextRetryAt ?? "", n.mastery]);
  }
  return toCsv(rows);
}

export function reportMarkdown(a: Analysis, cats: ErrorCategory[], recs: Recommendation[], previous?: Analysis): string {
  const s = scoreAnalysis(a);
  const lines: string[] = [];
  lines.push(`# ${a.title} — Exam analysis`, "", `Taken ${a.takenOn} · ${a.questions.length} questions · generated by Exam Pilot`, "");
  lines.push("## 1. Score summary", "", `- **Score:** ${fmtNum(s.score)} / ${fmtNum(s.maxScore)} (${fmtPct1(s.percentage)})`,
    `- **Attempt accuracy:** ${pct(s.accuracy)} (${s.correct} correct ÷ ${s.attempted} attempted)`,
    `- **Attempt rate:** ${pct(s.attemptRate)} (${s.attempted} of ${s.gradable})`,
    `- **Correct / wrong / unattempted:** ${s.correct} / ${s.wrong} / ${s.unattempted}${s.partial ? ` · partial ${s.partial}` : ""}`,
    `- **Negative-mark impact:** −${fmtNum(s.negativeImpact)}`, "");
  lines.push("## 2. Where the marks went", "", `- Left unattempted: −${fmtNum(s.forfeitedUnattempted)}`, `- Wrong answers (marks not earned + penalties): −${fmtNum(s.forfeitedWrong)}`, s.forfeitedPartial ? `- Partial-credit shortfall: −${fmtNum(s.forfeitedPartial)}` : "", "");
  lines.push("## 3. By subject", "", "| Subject | Score | Correct | Wrong | Unattempted | Accuracy |", "|---|---|---|---|---|---|");
  for (const r of breakdown(a, s, "subject")) lines.push(`| ${r.subject} | ${fmtNum(r.score)}/${fmtNum(r.max)} | ${r.correct} | ${r.wrong} | ${r.unattempted} | ${pct(r.accuracy)} |`);
  lines.push("", "## 4. Top mark-loss sources", "");
  for (const t of topLossSources(a, s, cats, 6)) lines.push(`- **${t.chapter}** (${t.subject}): −${fmtNum(t.forfeited)} — ${t.wrong} wrong, ${t.unattempted} unattempted${t.dominantError ? `; mostly ${t.dominantError.label.toLowerCase()}` : ""}`);
  lines.push("", "## 5. Why marks were lost", "");
  for (const e of errorBreakdown(a, s, cats)) lines.push(`- ${e.label}: ${e.count} question${e.count === 1 ? "" : "s"}, −${fmtNum(e.forfeited)}`);
  lines.push("", "## 6. Recommended next actions", "");
  recs.forEach((r, i) => lines.push(`${i + 1}. **${r.title}** — ${r.detail}  \n   _Evidence: ${r.reason}_`));
  if (previous) {
    const e = explainChange(s, scoreAnalysis(previous));
    lines.push("", "## 7. Compared with the previous test", "", `${previous.title}: ${fmtNum(scoreAnalysis(previous).score)} → ${fmtNum(s.score)}. ${e.narrative}`);
  }
  lines.push("", "## Questions to redo", "");
  for (const q of a.questions.filter((x) => s.byId[x.id]?.status === "wrong").sort((x, y) => x.index - y.index)) {
    const r = a.responses[q.id];
    lines.push(`- Q${q.index} (${q.chapter || q.subject}): you ${formatResponse(q, r)}, key ${formatKey(q)}${r?.errorPrimary ? ` — ${cats.find((c) => c.id === r.errorPrimary)?.label ?? r.errorPrimary}` : ""}`);
  }
  return lines.filter((l, i, arr) => !(l === "" && arr[i - 1] === "")).join("\n");
}

export function backupJson(data: AppData): string {
  return JSON.stringify({ app: "exam-pilot", exportedAt: new Date().toISOString(), data }, null, 2);
}

export function parseBackup(text: string): AppData {
  const parsed = JSON.parse(text);
  const data = parsed?.data ?? parsed;
  if (!data || !Array.isArray(data.exams) || !Array.isArray(data.analyses) || !data.settings) throw new Error("This file isn't an Exam Pilot backup.");
  return data as AppData;
}
